<Project>
  <PropertyGroup>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(Configuration)' == 'Release'">true</ContinuousIntegrationBuild>
    <DebugType Condition="'$(Configuration)' == 'Release'">none</DebugType>
    <DebugSymbols Condition="'$(Configuration)' == 'Release'">false</DebugSymbols>
    <PathMap Condition="'$(Configuration)' == 'Release'">$(MSBuildProjectDirectory)=/_/$(MSBuildProjectName)</PathMap>
  </PropertyGroup>
</Project>
